services:
  secretzitel333-telegram-bot:
    build: .
    container_name: secretzitel333-telegram-bot
    restart: always

    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"