[project]
name = "telegram-bot"
version = "0.1.0"
description = "Telegram bot with key phrase detection and owner notifications"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.1.1",
    "python-telegram-bot==21.2",
]
